### ISSUE TITLE
Go 1.4 Canonical Import Path comments are not rewritten

### ISSUE THREAD

**Issue by noonien** [kardianos/vendor#17]
Comments such as [theese](https://github.com/kardianos/osext/blob/master/osext.go#L6) produce errors while building.

    code in directory internal/github.com/kardianos/osext expects import "github.com/kardianos/osext"

**Comment by kardianos** [comment]
Could you make sure you have the latest version? It should remove those
references.

**Comment by noonien** [comment]
Indeed it does, thanks!

**Comment by kardianos** [comment]
Great!
