### ISSUE TITLE
Rewrite import paths in all packages that share the same dependency

### ISSUE THREAD

**Issue by mariash** [kardianos/vendor#18]
If several packages require the same dependency during `vendor add` only one of the packages will have its imports overwritten. 

This happens because when adding dependencies the imports rewrite is skipped if package files exist locally. https://github.com/kardianos/vendor/blob/master/rewrite/command.go#L233

To reproduce, here is an example: https://gist.github.com/mariash/6a48e89f18b9dd7a73a8
bosh-utils and main package share the same dependency `github.com/pivotal-golang/clock`. Only bosh-utils imports will be overwritten. Main package import for `github.com/pivotal-golang/clock` will remain the same.

**Comment by kardianos** [comment]
Fixed in 783925603a9f2febeef8c9e4242946ca64ec506b
