### ISSUE TITLE
Document GOPATH is required for use.

### ISSUE THREAD

**Issue by gmlewis** [kardianos/vendor#8]
If I create a Go app (using `package main`) somewhere outside of my `$GOPATH`, `vendor init` works, but `vendor list` and `vendor add -status external` both fail with the error:

```
Error: Package "/usr/local/google/home/gmlewis/src/scenarios/scenario1-2" not a go package or not in GOPATH.
```

Am I doing something wrong?
Thanks!

**Comment by kardianos** [comment]
I'll add a note to the readme.

vendor operates by re-writing import paths. The go tool will not be able to find the re-written import paths outside of GOPATH. The vendor file must write the new local path relative to the GOPATH as well.

GOPATH is requried.
